version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            venv/bin/pip3 install --upgrade pip
            venv/bin/python3 setup.py install
            venv/bin/pip3 install selenium==4.0.0a6.post2
      - run:
          command: |
            chromedriver --version
          name: Check chrome driver install
      - run:
          command: |
            mkdir screenshots
      - run:
          command: |
            . venv/bin/activate
            python3 -m unittest
      - store_artifacts:
          path: /home/circleci/project/test/tmp
          destination: screenshots
      - store_test_results:
          path: test-reports/
